[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
log = "0.4.22"
serde_json = "1.0.118"
sqlx = { version = "0.7", features=["runtime-tokio", "postgres"] }
serde = "1.0.193"